// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-maple/nop-kratos-demo/server/internal/biz"
	"github.com/go-maple/nop-kratos-demo/server/internal/conf"
	"github.com/go-maple/nop-kratos-demo/server/internal/server"
	"github.com/go-maple/nop-kratos-demo/server/internal/service"
)

// Injectors from wire.go:

func wireApp(string2 string, confServer *conf.Server, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	greeterUsecase := biz.NewGreeterUsecase(logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	registrar := server.NewRegistrar(string2, registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
	}, nil
}
